services:

  django:
    build:
      context: ./django
    container_name: django
    volumes:
      - ./static:/static
    depends_on:
      - postgres
    expose:
      - "8000"
    env_file:
      - ./.env/dev.env
    networks:
      - transcendence

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "8443:443"
    volumes:
      - ./static:/static
    networks:
      - transcendence
    depends_on:
      - django

  postgres:
    image: postgres:17.2-alpine3.21
    container_name: postgres
    expose:
      - "5432"
    env_file:
      - ./.env/dev.env
    volumes:
      - ./.data:/var/lib/postgresql/data
      - ./psql/:/docker-entrypoint-initdb.d
    networks:
      - transcendence

networks:
  transcendence:
    driver: bridge

volumes:
  data:
  static:

