services:

  django:
    build:
      context: ./django
    container_name: django
    volumes:
      - ./django:/usr/src/app
      - socket_volume:/app/django/sockets
      - socket_sql:/var/run/postgresql
    depends_on:
      - postgres
    expose:
      - "8000"
    env_file:
      - ./.env/dev.env
    networks:
      - transcendence

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "8443:443"
    volumes:
      - ./static:/static
      - ./django:/app/django
      - socket_volume:/app/django/sockets
      
    networks:
      - transcendence
    depends_on:
      - django

  postgres:
    container_name: postgres
    build:
      context: ./psql
    expose:
      - "5432"
    env_file:
      - ./.env/dev.env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - socket_sql:/var/run/postgresql
    networks:
      - transcendence
    restart: always

  # daphne:
  #   container_name: daphne
  #   build: ./daphne 
  #   env_file:
  #     - ./.env/dev.env
  #   command: daphne -u /app/django/sockets/daphne.sock mainApp.asgi:application
  #   volumes:
  #     - ./django:/app/django
  #     - socket_volume:/app/django/sockets
  #     - socket_sql:/var/run/postgresql
  #   networks:
  #     - transcendence

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - transcendence


networks:
  transcendence:
    driver: bridge

volumes:
  data:
  static:
  pgdata:
  socket_volume:
  socket_sql:
  

