# Generated by Django 4.1.13 on 2025-02-20 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmakingApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='ready',
        ),
    ]
