# Generated by Django 4.1.13 on 2025-03-17 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
