# Generated by Django 4.1.13 on 2025-03-18 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatApp', '0004_chatmodel_chatnotification_userprofilemodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='chatnotification',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='chatnotification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatModel',
        ),
        migrations.DeleteModel(
            name='ChatNotification',
        ),
        migrations.DeleteModel(
            name='UserProfileModel',
        ),
    ]
