#!/bin/sh

psql -U "$POSTGRES_USER" -c "CREATE DATABASE $DB;"

psql -U "$POSTGRES_USER" -c "CREATE USER $DB_USER WITH PASSWORD '$DB_PASSWORD';"

psql -U "$POSTGRES_USER" -c "GRANT ALL PRIVILEGES ON DATABASE $DB TO $DB_USER;"

psql -U "$POSTGRES_USER" -d "$DB" -c "GRANT ALL ON SCHEMA public TO $DB_USER;"