# Generated by Django 4.1.13 on 2025-04-02 13:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('scores', models.JSONField(default=None)),
                ('game_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('players', models.ManyToManyField(related_name='game_history', to='userManagementApp.playerprofile')),
            ],
        ),
    ]
