# Generated by Django 4.1.13 on 2025-04-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameStatsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='creation',
            field=models.DateTimeField(),
        ),
    ]
