# Generated by Django 4.1.13 on 2025-03-27 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import userManagementApp.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='', max_length=5)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=userManagementApp.models.set_profile_image_path)),
                ('is_online', models.BooleanField(default=False)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('friends', models.ManyToManyField(blank=True, to='userManagementApp.playerprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('scores', models.JSONField()),
                ('game_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('desertor', models.IntegerField(default=None, null=True)),
                ('players', models.ManyToManyField(related_name='game_history', to='userManagementApp.playerprofile')),
            ],
        ),
    ]
