# Generated by Django 4.1.13 on 2025-03-06 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='', max_length=5)),
                ('teeth_length', models.IntegerField(default=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('scores', models.JSONField()),
                ('game_id', models.UUIDField(editable=False, unique=True)),
                ('game_type', models.CharField(max_length=30)),
                ('desertor', models.IntegerField(default=None, null=True)),
                ('players', models.ManyToManyField(related_name='game_history', to='userManagementApp.playerprofile')),
            ],
        ),
    ]
