# Generated by Django 4.1.13 on 2025-04-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='nickname',
            field=models.CharField(default='', max_length=15),
        ),
    ]
