# Generated by Django 4.1.13 on 2025-03-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='has_profile_pic',
            field=models.BooleanField(default=False),
        ),
    ]
