# Generated by Django 4.1.13 on 2025-02-18 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='has_profile_pic',
        ),
    ]
