# Generated by Django 4.1.13 on 2025-02-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagementApp', '0002_remove_playerprofile_has_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='teeth_length',
            field=models.IntegerField(default=2),
        ),
    ]
