# Generated by Django 4.1.13 on 2025-02-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagementApp', '0002_remove_playerprofile_has_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='has_profile_pic',
            field=models.BooleanField(default=False),
        ),
    ]
